#!/usr/bin/env python3
"""
Alert Manager Module

Handles security alerts generated by the USB Security Gateway.

Responsibilities:
? Generate alerts
? Store alerts in SQLite database
? Log security events

Author: USB Security Gateway
"""

import os
import time

from gateway.alerts.logger import log_security_event, log_info
from gateway.database.db import insert_alert

def create_alert(alert_type, description, device_node=None):
    """
    Create and store a security alert.

    Parameters:
        alert_type (str) : type of alert
        description (str) : description of event
        device_node (str) : affected device
    """

    try:

        timestamp = int(time.time())

        alert_data = {
            "timestamp": timestamp,
            "alert_type": alert_type,
            "description": description,
            "device_node": device_node
        }

        # Log alert
        log_security_event(
            f"ALERT [{alert_type}] {description} Device: {device_node}"
        )

        # Store alert in database
        insert_alert(alert_data)

        log_info("Security alert stored in database")

        return alert_data

    except Exception as e:

        log_security_event(f"Alert generation failed: {str(e)}")

        return None


def create_device_block_alert(device_node):
    """
    Alert when a device is blocked.
    """

    return create_alert(
        "DEVICE_BLOCKED",
        "Suspicious USB device was blocked",
        device_node
    )


def create_malware_alert(device_node, infected_files):
    """
    Alert when malware is detected in USB files.
    """

    description = f"Malware detected in USB files: {infected_files}"

    return create_alert(
        "MALWARE_DETECTED",
        description,
        device_node
    )


def create_suspicious_device_alert(device_node, reasons=None):
    """
    Alert when suspicious firmware behavior is detected.
    
    Parameters:
        device_node (str): The device path
        reasons (list): List of reasons why device is suspicious
    """
    
    if reasons is None:
        reasons = []
    
    # Format reasons into description
    if reasons:
        description = "Suspicious USB firmware behavior detected:\n  • " + "\n  • ".join(reasons)
    else:
        description = "Suspicious USB firmware behavior detected"

    return create_alert(
        "SUSPICIOUS_USB",
        description,
        device_node
    )
