#!/usr/bin/env python3
"""
Scan Routes

Provides API endpoints for malware scan reports
generated by the sandbox analysis system.
"""

from flask import Blueprint, jsonify
import logging

from gateway.database.db import get_recent_malware_reports

scan_routes = Blueprint("scan_routes", __name__)

logger = logging.getLogger("Scan-Routes")


@scan_routes.route("/scan_results", methods=["GET"])
def get_scan_results():
    """
    Return malware scan reports.
    """

    try:

        reports = get_recent_malware_reports()

        return jsonify({
            "status": "success",
            "count": len(reports),
            "reports": reports
        })

    except Exception as e:

        logger.error(f"Scan report retrieval failed: {str(e)}")

        return jsonify({
            "status": "error",
            "message": "Failed to retrieve scan reports"
        }), 500


@scan_routes.route("/scan_results/recent", methods=["GET"])
def get_recent_scan_reports():
    """
    Return last 10 scan reports.
    """

    try:

        reports = get_recent_malware_reports(limit=10)

        return jsonify({
            "status": "success",
            "reports": reports
        })

    except Exception as e:

        logger.error(f"Recent scan report query failed: {str(e)}")

        return jsonify({
            "status": "error"
        }), 500
